### PR TITLE
Close #1 (Saved search queries)

### LINKED ISSUE #1: Feature request
Hi,

First of all, kudos, this app fills a gap in django admin UX.

It would be nice to have a save query button, and a select menu in the search bar to re-use them.

Keep the good work!

### PR DESCRIPTION
**Pull request by artinnok**

### CODE REVIEW

**Comment by stebunovd** [comment]
Hey @artinnok,

thank you for your interest in this project and for contributing! I have tested this on my machine, and in general, it worked. However, some improvements need to be made before we could consider merging it. Please see my comments below:

1. Your `FavoriteQuery` model is not linked to Django models in any way. It means that the same saved queries are shown for all models in Django admin. It represents a major problem because queries contain filters on particular model fields and relationships, and therefore will not work (or make any sense) if applied to other models;

2. Saved queries in your implementation don't have names. I suppose names should be useful from users' perspective since they allow to quickly refer to a particular query or just understand a query does (especially true for long, complex queries);

3. When I choose a saved query from the list, it's body is copied into the query input but nothing happens after that. I guess the expected action for a user would be that a query is applied right after you selected it, i.e. that the page is reloaded and a user can see filtered results and a query name of a current query (see note above query names above);

4. Once the list of saved queries is shown the only way to hide it is to click on the "Close" icon above. I suppose the more user-friendly approach would be to close the list upon click on any area outside of the list;

5. As far as I can see "shared/private queries" feature is not supported yet. In your code I see a comment related to it, I guess you were also thinking about it, probably you just didn't have enough time to implement it;

6. In which browsers have you tested your code? I see that you use `fetch()` method which is not supported in IE, so there's at least one major compatibility problem there (and there could be more). For DjangoQL we declare compatibility with IE9+ and all major desktop browsers;

7. In your JavaScript code I see that you use `.addEventListener()` to add your event handlers, but I don't see where do you remove these handlers. So I guess there should be memory leaks when those items are removed from the DOM;

8. There's no need to replace relative imports to absolute ones as you did in https://github.com/artinnok/djangoql/commit/4c9372e1e1300da372ca9e9783de3185fc10b826 The "ImportError" problem most likely comes from the way you set up your local development environment, this is not a problem in the library itself;

9. For a single feature 51 commit is probably too much :) It's hard to read and review, I'd prefer to keep project history more compact and clean. Could you please organize it in less number of commits?

10. I'm not sure what is the rationale behind having `favorite_query_save` flag in `DjangoQLFavoriteQueryMixin`since this flag effectively disables all mixin features. It seems like a duplication of the same function. If users don't want to enable favorite query feature for a particular admin class, they would simply not add the mixin there;

11. That would be nice to give migrations friendly names instead of auto-generated ones so that we could see right from the migration name what does this migration do. Also, 4 migrations to create a single model from scratch is an overhead I think, that should be done with one migration;

12. That's nice that you wrote a readme for a test project setup, and have even added a fixture with test data. However, I'd like to mention that `requirements.txt` with a fixed Django version of 1.11.6 looks slightly misleading because the library is intended to work with all Django versions starting with 1.8 or later. BTW did you test how it looks in Django 1.8?

13. For this new feature, you have provided no tests. That would be nice to have them.

I have more items which attracted my attention in this solution, but I'm not mentioning them right now because they are probably less important. Maybe we could return to them later if more important items above get fixed.


thanks,

Denis

**Comment by artinnok** [comment]
Hey @stebunovd,

Thanks for your comments, I tried to take into account:

1. Fixed;
2. I have seen this feature in issue, but can't imagine it UI - because of it, it was't implemented. If you help me with UI design that will simple and functional, certainly, I can do it;
3. Fixed;
4. Fixed;
5. Implemented;
6. What approach I can use for support IE9+? Maybe polyfill?
7. Fixed;
8. Fixed;
9. Fixed;
10. Fixed;
11. Fixed;
12. Manually tested with Django 1.8.16, Python 2.7.3. Also, as I can see, Travis CI has tests for Django 1.8-1.11 and Python 2.7-3.6;
13. Fixed;

**Comment by stebunovd** [comment]
Hey @artinnok,

wow - I'm impressed by a quick turnaround, a lot of items from my list above are fixed, good job!

However, the most important problem is still there. You're asking for a UI for query names, but to be honest I don't have an easy answer for this. From my perspective, this is the main complexity in this task - finding a good UI solution, which would be user-friendly and simple enough. I have some raw ideas, but they worth nothing without real experiments, and also there could be implementation challenges. That's the main reason why I prefer not to announce them in a form of an implementation guide because it can be quite misleading. Real experiments can prove that these ideas are not good enough, and other ideas may arise instead. That's why I suppose that UX ideas should ideally be explored by the same person who does the implementation.

Another item that I'd like to mention in your solution is the way in which you implemented shared/private queries. In your version, it's configured on per-model bases in the admin code, via `public_favorite_query_enabled` flag. I'm not sure which use cases does this implementation address. I thought that the case for shared queries would be users deciding which queries to share, i.e. Alice is sharing _some of her queries_ publicly so that Bob can use them as well. I can imagine real use cases for that, such as more experienced users are helping others to build a complex query, or sharing queries that have a special meaning for business so that users can rely on them in particular business processes. In your implementation queries sharing is controlled by an application developer, not by end users, and there's no way to for a user to share just some of her queries, it shares either all queries from all users or nothing.

There're still some items in the code that may need attention, like deciding what to use instead of `fetch`, or finally getting rid of absolute imports in the library, etc., but I suppose they are less important. The main challenge seems to be good UX, as I mentioned above. 


thanks,

Denis

**Comment by artinnok** [comment]
Hey @stebunovd,

1. Implemented functionality for query names;
2. Implemented functionality for shared / private queries.

It's OK? I'm waiting for your comments, Denis. 

Thanks, Artem

**Comment by stebunovd** [comment]
Hey Artem,

here are my thoughts. First, I'll paste a screenshot here, as an illustration for comments below:
screen shot 2017-11-10 at 11 52 18

Overall, I think that this new interface is richer in features than the first version, however UX is still far from perfect:

1. Query names are not shown anywhere when a query is applied, so users don't get a visual confirmation that the current query is the one that they want;

2. When you save a new query, it doesn't ask for a name but saves it with autogenerated name instead. So to save a query under a custom name users have to: A) click Save icon; B) click "book" icon; C) find their new query in the list and click "Edit" on the name; D) enter new name and click "apply". I suppose by default users will likely want to give names to their queries, so the whole flow could be as simple as A) click Save; B) enter a name in a dialog and click "apply". Also, I'd like to mention that the method which you use to generate default query names doesn't guarantee their uniqueness, and you don't have any errors handling for that;

3. In the interface, you suggest to edit query body in a small dedicated input. So we have 2 inputs for the same thing - one large with autocompletion, and another - small without autocompletion. If we allow editing of query body, I suppose it should be identical for the input which we use for new queries, the same size and with autocompletion. Also, if you try to edit large queries inside that small input that would be inconvenient and error-prone;

4. when you hover mouse over rows in stored queries list, the whole row becomes highlighted and that gives an impression that when you click it, the query should be applied, however, nothing happens when you click on it. It turns out that to apply a query you actually have to click a small "search" icon. I guess it could be confusing for many users;

5. icons are not lined up for shared / private queries, see screenshot above;

6. visual confirmation of actions in the interface is not consistent. When you click "Save" icon, there's a brief flash of the icon, which gives a visual confirmation that the action is complete. However for other actions, such as edit query name or change its visibility there's no such confirmation. Also, confirmation for "Save" icon is, in fact, artificial, it doesn't reflect actual operation status;

7. there's no clear distinction between shared and private queries, they appear in the same list without any ordering. I guess that could be helpful to split them into two lists, one with shared queries, and another with private;

8. use of radio button for a binary action seems to be an overkill. I guess it could be done in a more clear and concise way by either using a checkbox or an icon that flips it's state, or by moving a query from one list to another (see an item 7 above);

Items from my previous comments that were not addressed:
- I don't think it makes sense to restrict access to editing shared queries to their authors only;
- you're still using absolute imports in the library;
- migration with an autogenerated name for the test project.

Besides that, I also have other thoughts on the code, in particular about javascript code structure. However these are probably less important. From my perspective UX still remains the main problem to solve. If we could solve UX, other items should be relatively simple.


thanks,

Denis

**Pull request closed without merging**
