### PR TITLE
feat: allow search in binary fields

### PR DESCRIPTION
**Pull request by Akay7**

### CODE REVIEW

**Comment by stebunovd** [comment]
Hi @Akay7, could you please rebase your work from the mater? I'm trying to make the checks work with pull requests, and the change is already in master, but still fails if you re-run it with your pull request. I suspect that it might be using the job definition from your fork, which doesn't have the necessary condition yet.

**Comment by Akay7** [comment]
Hi @stebunovd , I made a rebase. But seems it doesn't help done jobs correctly. Please let me know if I could be useful.

**Comment by stebunovd** [comment]
yep, it didn't work. Can we do another attempt? I changed it to run on event_name instead of repo owner. Could you please rebase once again?

**Comment by Akay7** [comment]
@stebunovd still same. I'm ready for new rebases.

**Comment by Akay7** [comment]
@stebunovd hooray worked!

**Comment by stebunovd** [comment]
oh cool, we made it working by skipping all of the tests! LOL. I hope it'll be a final one - I have removed test dependency from the notification job, so hopefully now it should work. Could you please rebase once again?

**Comment by Akay7** [comment]
> Could you please rebase once again?

Done!

**Comment by stebunovd** [comment]
woo-hoo, we did it! Your change is now merged and included in v0.14.2 which is already on PyPI. Thanks!

**Comment by smiling-watermelon** [comment]
Hi!
I'm not sure if this should be addressed in a new issue, however it seems like search on binary fields doesn't work for some dialects of SQL, for example - PostgreSQL:
If I make a request like:
```python
my_hash_field = "hexvalueofthehash"
```
Instead of getting no results or getting the results with matching hash, I get an error 500.

```
string argument without an encoding
```

An example of the `str(qs.query)`:
```sql
SELECT
    "my_app_name_paymentdetails"."uuid",
    "my_app_name_paymentdetails"."created_at",
    "my_app_name_paymentdetails"."updated_at",
    "my_app_name_paymentdetails"."my_hash_field"
FROM
    "my_app_name_paymentdetails"
WHERE
    "my_app_name_paymentdetails"."my_hash_field" = Binary('6d62db5bbfa...')
ORDER BY
    "my_app_name_paymentdetails"."created_at" DESC,
    "my_app_name_paymentdetails"."uuid" DESC
```

Perhaps a more appropriate place to complain would be the translator to PostgreSQL from the QS?

However, I'll note that searching with `~` (contains) works for me, and produces the following SQL query:
```sql
SELECT
    "my_app_name_paymentdetails"."uuid",
    "my_app_name_paymentdetails"."created_at",
    "my_app_name_paymentdetails"."updated_at",
    "my_app_name_paymentdetails"."my_hash_field"
FROM
    "my_app_name_paymentdetails"
WHERE
    UPPER("my_app_name_paymentdetails"."my_hash_field"::text) LIKE UPPER(%6d62db5bbfa...%)
ORDER BY
    "my_app_name_paymentdetails"."created_at" DESC,
    "my_app_name_paymentdetails"."uuid" DESC
```

**Comment by Akay7** [comment]
Hi @smiling-watermelon 

> I'm not sure if this should be addressed in a new issue, however it seems like search on binary fields doesn't work for some dialects of SQL, for example - PostgreSQL:

1. Please show QL query
2. Definition of the hash field from django model
2. Tell version of postgres
3. And version of Django

My fix was done especially for project that used Postgres, _but time flies and maybe something broken now._

**Comment by smiling-watermelon** [comment]
@Akay7, thanks for swift response.

QL Query:
```
payment_method_hash = "6d62db5bbfa3d7db8008fb44b4bfad755c4a26dce339a7cd830bc7539ec45d06338c9648e3019c3e4e91234466f70d4cc50bfcd4a3baaf641054af80a5e86516"
```
image
(It looks a bit ugly because of a clash with the theme we're using in our app)


Hash Field is defined as such:
```python
    payment_method_hash = models.BinaryField(
        max_length=512,
        verbose_name=_("Payment method hash"),
        null=True,
    )
```

The hierarchy of models, if it matters in any way.
```python
from django.db import models

class BaseModelMixin(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    created_at = models.DateTimeField(
        verbose_name=_("created_at"),
        db_index=True,
        auto_now_add=True,
    )
    updated_at = models.DateTimeField(
        verbose_name=_("updated_at"),
        db_index=True,
        auto_now=True,
    )

    class Meta:
        abstract = True
        get_latest_by = "created_at"
        ordering = ("-created_at",)


# Class that defines the hash field
class PaymentDetailsBase(BaseModelMixin):
    payment_method_hash = models.BinaryField(
        max_length=512,
        verbose_name=_("Payment method hash"),
        null=True,
    )

    # I'm searching in Django QL with the result of this property
    @property
    def hash_hex(self: "PaymentDetailsBase") -> str | None:
        if self.payment_method_hash is None:
            return None
        return self.payment_method_hash.hex()

    class Meta(BaseModelMixin.Meta):
        abstract = True

# This is the class I'm doing the search on
class PaymentDetails(PaymentDetailsBase):
    pass
    # Other unrelated fields
```


I'm using PostgreSQL of version 16.12 (Debian 16.12-1.pgdg13+1); From what I know - same applies on 16.13 to my colleagues.


Django version is 6.0.7 with Python 3.12.13 on Linux.
Other packages that might be related:
```
djangoql==0.19.1
psycopg==3.3.4
```

However, if I remember correctly, same problem occurred in 5.2.* releases of Django.

From my local debugging - the field is correctly identified as a BinaryField by DjangoQL, but since it treats them as strings (in `DjangoQLSchema.get_field_cls`), it might not be applying conversions to binary from string :thinking:

**Comment by Akay7** [comment]
Thanks @smiling-watermelon. I think it's psycopg3 broke that functionality in your case.

Hi @stebunovd ! I prepared another PR https://github.com/ivelum/djangoql/pull/131 for described issue.

**Pull request merged**
